package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"errors"

	"github.com/riyadennis/pbac/graph/generated"
	"github.com/riyadennis/pbac/graph/model"
	internalmodel "github.com/riyadennis/pbac/internal/model"
	"github.com/riyadennis/pbac/internal/repository"
)

// CreatePolicy is the resolver for the createPolicy field.
func (r *mutationResolver) CreatePolicy(ctx context.Context, input model.CreatePolicyInput) (*internalmodel.Policy, error) {
	return r.svc.Create(ctx, &internalmodel.CreatePolicyRequest{
		Name:        input.Name,
		Description: input.Description,
		Module:      input.Module,
		Content:     input.Content,
	})
}

// UpdatePolicy is the resolver for the updatePolicy field.
func (r *mutationResolver) UpdatePolicy(ctx context.Context, id string, input model.UpdatePolicyInput) (*internalmodel.Policy, error) {
	return r.svc.Update(ctx, id, &internalmodel.UpdatePolicyRequest{
		Name:        input.Name,
		Description: input.Description,
		Module:      input.Module,
		Content:     input.Content,
	})
}

// DeletePolicy is the resolver for the deletePolicy field.
func (r *mutationResolver) DeletePolicy(ctx context.Context, id string) (bool, error) {
	err := r.svc.Delete(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// EvaluatePolicy is the resolver for the evaluatePolicy field.
func (r *mutationResolver) EvaluatePolicy(ctx context.Context, id string, input model.EvaluateInput) (*model.EvaluateResult, error) {
	req := &internalmodel.EvaluateRequest{
		Input: input.Input,
	}
	if input.Query != nil {
		req.Query = *input.Query
	}

	resp, err := r.svc.Evaluate(ctx, id, req)
	if err != nil {
		return nil, err
	}

	return &model.EvaluateResult{
		Result: resp.Result,
		Allow:  resp.Allow,
	}, nil
}

// Policy is the resolver for the policy field.
func (r *queryResolver) Policy(ctx context.Context, id string) (*internalmodel.Policy, error) {
	policy, err := r.svc.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return policy, nil
}

// Policies is the resolver for the policies field.
func (r *queryResolver) Policies(ctx context.Context) ([]*internalmodel.Policy, error) {
	policies, err := r.svc.List(ctx)
	if err != nil {
		return nil, err
	}
	if policies == nil {
		return []*internalmodel.Policy{}, nil
	}
	return policies, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
