// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePolicyInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Module      string `json:"module"`
	Content     string `json:"content"`
}

type EvaluateInput struct {
	Input map[string]any `json:"input,omitempty"`
	Query *string        `json:"query,omitempty"`
}

type EvaluateResult struct {
	Result any  `json:"result,omitempty"`
	Allow  bool `json:"allow"`
}

type Mutation struct {
}

type Query struct {
}

type UpdatePolicyInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Module      string `json:"module"`
	Content     string `json:"content"`
}
